export const dict =  [
  "DESINSTITUTIONNALISATION",
  "ELECTROENCEPHALOGRAPHIES",
  "HYPOTHALAMOHYPOPHYSAIRES",
  "NEUROPSYCHOPHARMACOLOGIE",
  "PHOSPHATIDYLETHANOLAMINE",
  "POLYTETRAFLUOROETHYLENES",
  "STERNOCLEIDOMASTOIDIENES",
  "STERNOCLEIDOMASTOIDIENNE"
]