export const dict =  [
  "ANTICONSTITUTIONNELLEMENT",
  "DESINSTITUTIONNALISATIONS",
  "DESOXYRIBONUCLEOPROTEIQUE",
  "ELECTROCONVULSIVOTHERAPIE",
  "NEUROPSYCHOPHARMACOLOGIES",
  "OLIGOASTHENOTERATOSPERMIE",
  "PHOSPHATIDYLETHANOLAMINES",
  "STERNOCLEIDOMASTOIDIENNES"
]