export const dict =  [
  "CONSTITUTIONNALISATION",
  "DECONFESSIONNALISATION",
  "DEPROFESSIONNALISATION",
  "DISPROPORTIONNELLEMENT",
  "ELECTROCARDIOGRAPHIQUE",
  "ELECTROENCEPHALOGRAMME",
  "ELECTROENCEPHALOGRAPHE",
  "HYPERCHOLESTEROLEMIQUE",
  "HYSTEROSALPINGOGRAPHIE",
  "INTERGOUVERNEMENTALITE",
  "OTORHINOLARYNGOLOGIQUE",
  "OTORHINOLARYNGOLOGISTE",
  "STERNOCLEIDOMASTOIDIEN"
]